name: dragoma
description: dragoma flutter project
version: 1.0.0+1000000
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # 三方库
  cupertino_icons: ^1.0.1+1
  audioplayers: ^0.20.1
  auto_size_text: ^3.0.0-nullsafety.0
  bot_toast: ^4.0.1
  cached_network_image: ^3.1.0
  day: ^0.7.1
  decimal: ^1.5.0
  device_info_plus: ^4.0.0
  dio: ^4.0.0
  event_bus: ^2.0.0
  flutter_native_contact_picker: ^0.0.3
  intl: ^0.17.0
  json_annotation: ^4.3.0
  moor: ^4.6.1+1
  package_info: ^2.0.2
  path_provider: ^2.0.8
  provider: ^6.0.2
  permission_handler: ^8.3.0
  photo_view: ^0.13.0
  rxdart: ^0.27.3
  shared_preferences: ^2.0.9
  shimmer: ^2.0.0
  sqlite3_flutter_libs: ^0.5.1
  url_launcher: ^6.0.15
  video_player: ^2.2.7
  archive: ^3.1.6
  get: ^4.6.1
  pedometer: ^3.0.0

  # fork的三方库
  geolocator:
    git:
      url: git@github.com:DragomaApp/lib_flutter_packages.git
      path: packages/geolocator
      ref: master
  photo_manager_patch:
    git:
      url: git@github.com:DragomaApp/lib_flutter_packages.git
      path: packages/photo_manager_patch
      ref: master
  shimmer_animation:
    git:
      url: git@github.com:DragomaApp/lib_flutter_packages.git
      path: packages/shimmer_animation
      ref: master
  wifi:
    git:
      url: git@github.com:DragomaApp/lib_flutter_packages.git
      path: packages/ylz_wifi
      ref: master
  wechat_assets_picker:
    git:
      url: git@github.com:DragomaApp/lib_flutter_packages.git
      path: packages/wechat_assets_picker
      ref: master
  connectivity:
    git:
      url: git@github.com:DragomaApp/lib_flutter_packages.git
      path: packages/connectivity
      ref: master
  flutter_image_compress:
    git:
      url: git@github.com:DragomaApp/lib_flutter_packages.git
      path: packages/flutter_image_compress
      ref: master

  # 自有库
  lib_ylz_upgrade_package:
    git:
      url: git@github.com:DragomaApp/lib_flutter_packages.git
      path: packages/lib_ylz_upgrade_package
      ref: master
  lib_ylz_camera:
    git:
      url: git@github.com:DragomaApp/lib_flutter_packages.git
      path: packages/lib_ylz_camera
      ref: master
  lib_ylz_router_package:
    git:
      url: git@github.com:DragomaApp/lib_flutter_packages.git
      path: packages/lib_ylz_router_package
      ref: master
  lib_ylz_ui_kit_package:
    git:
      url: git@github.com:DragomaApp/lib_flutter_packages.git
      path: packages/lib_ylz_ui_kit_package
      ref: master
  lib_ylz_utils_package:
    git:
      url: git@github.com:DragomaApp/lib_flutter_packages.git
      path: packages/lib_ylz_utils_package
      ref: master
  nh_flutter_native_channel:
    git:
      url: git@github.com:DragomaApp/lib_flutter_packages.git
      path: packages/nh_flutter_native_channel
      ref: master
  nh_flutter_network:
    git:
      url: git@github.com:DragomaApp/lib_flutter_packages.git
      path: packages/nf_flutter_network
      ref: master
  lib_ylz_webview_core_x5:
    git:
      url: git@github.com:DragomaApp/lib_flutter_packages.git
      path: packages/lib_ylz_webview_core_x5
      ref: master
  lib_ylz_page_lifecycle:
    git:
      url: git@github.com:DragomaApp/lib_flutter_packages.git
      path: packages/lib_ylz_page_lifecycle
      ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  build_runner: ^2.1.5
  git_hooks: 0.1.6
  json_serializable: ^6.0.1
  moor_generator: ^4.5.1

dependency_overrides:
  provider: ^6.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/guide/
    - assets/images/tab/
